CREATE DATABASE `CYBERNINJA_STORE_SYS` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE CYBERNINJA_STORE_SYS;
CREATE TABLE `CUSTOMERS` (
  `CUSTOMER_ID` bigint NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `LAST_PURCHASE_DATE` date DEFAULT NULL,
  `LOCALITY` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `POSTAL_CODE` varchar(255) NOT NULL,
  `PROVINCE` varchar(255) NOT NULL,
  `REGION` varchar(255) NOT NULL,
  `SURNAME` varchar(255) NOT NULL,
  `TELEPHONE` varchar(255) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ORDERS` (
  `ORDER_ID` bigint NOT NULL AUTO_INCREMENT,
  `PURCHASE_DATE` date NOT NULL,
  `TOTAL_PRICE` double NOT NULL,
  `CUSTOMER_ID` bigint NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  KEY `FK_ORDERS__CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `FK_ORDERS__CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` date DEFAULT NULL,
  `DESCRIPTION` varchar(1000) NOT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `PRICE_WOUT_DISCOUNT` double NOT NULL,
  `PURCHASE_PRICE` double NOT NULL,
  `SALE_PRICE` double NOT NULL,
  `TOTAL_PRICE` double NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DOCUMENTS` (
  `DOCUMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SIZE` bigint NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `PICTURE` longblob NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  PRIMARY KEY (`DOCUMENT_ID`),
  KEY `FK_DOCUMENTS__PRODUCT_ID` (`PRODUCT_ID`),
  CONSTRAINT `FK_DOCUMENTS__PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUCTS_category` (
  `PRODUCTS_PRODUCT_ID` bigint NOT NULL,
  `CATEGORY` varchar(255) NOT NULL,
  PRIMARY KEY (`PRODUCTS_PRODUCT_ID`,`CATEGORY`),
  CONSTRAINT `FK_PRODUCTS_CATEGORY__PRODUCT_ID` FOREIGN KEY (`PRODUCTS_PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUCTS_colour` (
  `PRODUCTS_PRODUCT_ID` bigint NOT NULL,
  `COLOUR` varchar(255) NOT NULL,
  PRIMARY KEY (`PRODUCTS_PRODUCT_ID`,`COLOUR`),
  CONSTRAINT `FK_PRODUCTS_COLOUR__PRODUCT_ID` FOREIGN KEY (`PRODUCTS_PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUCTS_size` (
  `PRODUCTS_PRODUCT_ID` bigint NOT NULL,
  `SIZE` varchar(255) NOT NULL,
  PRIMARY KEY (`PRODUCTS_PRODUCT_ID`,`SIZE`),
  CONSTRAINT `FK_PRODUCTS_SIZE__PRODUCT_ID` FOREIGN KEY (`PRODUCTS_PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `REL_ORDER_PRODUCT` (
  `ORDER_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  KEY `FK_PRODUCTS__ORDER_ID` (`PRODUCT_ID`),
  KEY `FK_ORDERS__PRODUCT_ID` (`ORDER_ID`),
  CONSTRAINT `FK_ORDERS__PRODUCT_ID` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  CONSTRAINT `FK_PRODUCTS__ORDER_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USERS` (
  `USER_ID` bigint NOT NULL AUTO_INCREMENT,
  `AUTH_ATTEMPS` int DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `DELETE_TIME` datetime DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `LAST_PASS_CHANGE_DATE` datetime DEFAULT NULL,
  `LOCKED` bit(1) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `PASS_EXP_DATE` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `CUSTOMER_ID` bigint NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_USERNAME` (`USERNAME`),
  KEY `FK_USER__CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `FK_USER__CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USERS_roles` (
  `USERS_USER_ID` bigint NOT NULL,
  `ROLES` varchar(255) DEFAULT NULL,
  KEY `FK_USERS_ROLES__USER_ID` (`USERS_USER_ID`),
  CONSTRAINT `FK_USERS_ROLES__USER_ID` FOREIGN KEY (`USERS_USER_ID`) REFERENCES `USERS` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO CUSTOMERS 
(CUSTOMER_ID, ADDRESS, EMAIL, LAST_PURCHASE_DATE, LOCALITY, NAME, POSTAL_CODE, PROVINCE, REGION, SURNAME, TELEPHONE)
VALUES(1, '', '', NULL, '', '', '', '', '', '', '');

INSERT INTO USERS
(USER_ID, AUTH_ATTEMPS, CREATE_TIME, DELETE_TIME, ENABLED, LAST_PASS_CHANGE_DATE, LOCKED, PASSWORD, PASS_EXP_DATE, UPDATE_TIME, USERNAME, CUSTOMER_ID)
VALUES(1, 0, '1111-11-11 00:00:00', NULL, 1, '1111-11-11 00:00:00', 0, '$2a$10$Betrvo69Kq8dJ2pZ37avTua8ez./O4wlDv2GUhae4QU9tAJGAw09S', '6666-06-06 00:00:00', '1111-11-11 00:00:00', 'admin', 1);

INSERT INTO USERS_roles
(USERS_USER_ID, ROLES)
VALUES(1, 'ADMIN');